update the uEnv file, too

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -7,13 +7,29 @@
 DIRNAME="`dirname $0`"
 cd "$DIRNAME/.."
 
+die() {
+	echo >&2 "$*"
+	exit 1
+}
+
 cp dts/CAPE-BONE-OCTO-00A0.dtbo /lib/firmware
 
 if [ ! -d /etc/systemd ]; then
-	echo >&2 '/etc/systemd does not exist?  Is this not angstrom?'
-	exit 1
+	die "/etc/systemd does not exist?  Is this not angstrom?"
 fi
+
+BOOT=/media/BEAGLEBONE
+UENV="$BOOT/uEnv.txt"
+mount -t vfat /dev/mmcblk0p1 "$BOOT" || die "Failed to mount $BOOT"
+cp "$UENV" "$UENV.backup"
+
+cat <<END > "$UENV"
+optargs=quiet capemgr.disable_partno=BB-BONELT-HDMI,BB-BONELT-HDMIN
+END
+
+umount "$BOOT"
 
 cp bin/ledscape.service /etc/systemd/system/
 systemctl enable ledscape.service
 systemctl status ledscape.service
+
